---
root: true
env:
  es2017: true
  node: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - prettier
  - plugin:prettier/recommended
  - prettier/@typescript-eslint
  - plugin:filenames-simple/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2019
  sourceType: module
plugins:
  - '@typescript-eslint'
rules:
  '@typescript-eslint/explicit-module-boundary-types': off
overrides:
  - files:
      - src/utils/polyfill.node10.ts
    plugins:
      - filenames-simple
    rules:
      '@typescript-eslint/ban-ts-comment': off
      '@typescript-eslint/no-explicit-any': off
      filenames-simple/extname: off
