---
root: true
env:
  es2017: true
  node: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - prettier
  - plugin:prettier/recommended
  - prettier/@typescript-eslint
  - plugin:filenames-simple/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2019
  sourceType: module
overrides:
  - files:
      - '__tests__/**'
    plugins:
      - '@typescript-eslint'
      - filenames-simple
    rules:
      '@typescript-eslint/explicit-module-boundary-types': off
      filenames-simple/extname: off
