---
root: true
env:
  es2017: true
  node: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - prettier
  - plugin:prettier/recommended
  - prettier/@typescript-eslint
  - plugin:filenames-simple/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2019
  sourceType: module
plugins:
  - '@typescript-eslint'
rules:
  '@typescript-eslint/explicit-module-boundary-types': off
overrides:
  - files:
      - '__tests__/**'
    rules:
      filenames-simple/extname: off
