---
root: true
env:
  es2017: true
extends:
  - '@epaew/eslint-config/node-typescript'
  - plugin:filenames-simple/recommended
  - prettier
parserOptions:
  ecmaVersion: 2018
overrides:
  - files:
      - '__tests__/**'
    plugins:
      - '@typescript-eslint'
      - filenames-simple
    rules:
      '@typescript-eslint/explicit-module-boundary-types': off
