---
root: true
env:
  es2017: true
extends:
  - plugin:filenames-simple-node-18/recommended
  - prettier
parserOptions:
  ecmaVersion: 2018
overrides:
  - files:
      - '__tests__/**'
    plugins:
      - '@typescript-eslint'
      - filenames-simple-node-18
    rules:
      '@typescript-eslint/explicit-module-boundary-types': off
