name: Run Jest

on:
  pull_request: {}
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 */3 * *'

jobs:
  jest:
    name: Jest w/ Node:${{ matrix.node }} ESLint:${{ matrix.eslint }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node:
          - 10.x
          - 12.x
          - 14.x
        eslint:
          - 6
          - 7
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.4.0
        with:
          node-version: ${{ matrix.node }}
          cache: yarn
      - run: yarn install --frozen-lockfile

      - run: yarn add eslint@${{ matrix.eslint }}

      - name: yarn run test && report coverage
        uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: 03c045faa77d44bb865e441b9507cb2a6ee668a225962491ce40d37d6b297899
        with:
          coverageCommand: yarn test:ci
          coverageLocations: |
            ${{ github.workspace }}/coverage/lcov.info:lcov
          debug: true

      - name: Reset local changes
        run: git checkout . && yarn
